services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: reserve-beach-phpmyadmin
    environment:
      PMA_HOST: reserve-beach-mysql
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8081:80"
    networks:
      - reserve-beach
    restart: always

networks:
  reserve-beach:
    external: true