services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: reserve-beach-phpmyadmin
    environment:
      PMA_HOST: reserve-beach-mysql
      PMA_PORT: ${DB_PORT:-3306}
    ports:
      - "${PMA_PORT:-8081}:80"
    networks:
      - reserve-beach
    restart: on-failure

networks:
  reserve-beach:
    external: true