networks:
  reserve-beach:
    name: reserve-beach
    driver: bridge
    
services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: reserve-beach-nginx
    depends_on:
      - php
    ports:
      - "3004:80"
    volumes:
      - ./src/public:/var/www/html
    networks:
      - reserve-beach

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: reserve-beach-php
    volumes:
      - ./src:/var/www/html/src
      - ./public:/var/www/html/public
      - ./config:/var/www/html/config
      - ./var:/var/www/html/var
      - ./.env:/var/www/html/.env
    networks:
      - reserve-beach

  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    container_name: reserve-beach-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - reserve-beach

volumes:
  mysql_data: