networks:
  reserve-beach:
    name: reserve-beach
    driver: bridge
    
services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: reserve-beach-nginx
    depends_on:
      - php
    ports:
      - "3004:80"
    volumes:
      - ./src/public:/var/www/html
    networks:
      - reserve-beach
    restart: always

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: reserve-beach-php
    user: "${UID}:${GID}"
    environment:
      - UID=${UID}
      - GID=${GID}
    volumes:
      - ./src:/var/www/html/src
      - ./public:/var/www/html/public
      - ./config:/var/www/html/config
      - ./var:/var/www/html/var
      - ./.env:/var/www/html/.env
    networks:
      - reserve-beach
    restart: always

  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    container_name: reserve-beach-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      PMA_ABSOLUTE_URI: http://localhost:8081/
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - reserve-beach
    restart: always

volumes:
  mysql_data: