networks:
  reserve-beach:
    name: reserve-beach
    driver: bridge
    
services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: reserve-beach-nginx
    depends_on:
      - php
    ports:
      - "3004:80"
    volumes:
      - ./:/var/www/html/:cached
    networks:
      - reserve-beach
    restart: on-failure

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: reserve-beach-php
    volumes:
      - ./:/var/www/html/:cached
    networks:
      - reserve-beach
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mysql

  mysql:
    image: mysql:${MYSQL_VERSION:-9.2.0}
    container_name: reserve-beach-mysql
    ports:
      - ${DB_PORT:-8082}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-reserve_beach}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=America/Fortaleza
    volumes:
      - ./docker/sql/:/docker-entrypoint-initdb.d/
      - database_data:/var/lib/mysql
    networks:
      - reserve-beach

volumes:
  database_data:
